language: php

php:
    - 7.1

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit -c . --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 3d51f40d-45c8-43ad-9687-d26e010517e1

